language: node_js

node_js:
  - '10'

script:
  - npm install
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    email: 'hajnalbenjamin@gmail.com'
    api_key: NPM_TOKEN
    on:
      tags: true
